### ISSUE TITLE
Can I ignore the label when rend_field?

### ISSUE THREAD

**Issue by weickdev** [helloflask/bootstrap-flask#233] opened 2022-06-11 03:10 UTC
Can I only rend the Input , don't include the labe when i rend-field? Sometimes I want to design the label by myself?

**Comment by PanderMusubi** [comment] 2022-06-21 06:34
Duplicate of https://github.com/helloflask/bootstrap-flask/issues/47 ?

**Comment by greyli** [comment] 2022-08-20 10:14
Close as duplicated.

**Closed by greyli** 2022-08-20 10:14 UTC
